name: CI - Maven Tests

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to run tests against (local/staging/prod)'
        required: true
        default: 'local'
      groups:
        description: 'TestNG groups to run (comma-separated)'
        required: false
        default: 'smoke'
      tag:
        description: 'Optional tag for this run (for reporting)'
        required: false
        default: ''
      service_name:
        description: 'Kubernetes service name '
        required: true
        default: 'svc'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      ENV: ${{ github.event.inputs.env || 'local' }}
      GROUPS: ${{ github.event.inputs.groups || 'smoke' }}
      SERVICE_NAME: ${{ github.event.inputs.service_name || 'svc' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: |
          echo "Running tests for env=$ENV groups=$GROUPS service_name=$SERVICE_NAME"

          mvn -B \
            -Denv="$ENV" \
            -Dgroups="$GROUPS" \
            -Dheadless=true \
            -DrunMode=local \
            -DserviceName="$SERVICE_NAME" \
            test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            target/surefire-reports
            target/failsafe-reports